service: myapp

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: !GetAtt TasksTable.Arn

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  createTask:
    handler: handler.createTask
    events:
      - http:
          path: /tasks
          method: post
  getTaskById:
    handler: handler.getTaskById
    events:
      - http:
          path: /tasks/{id}
          method: get

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasksTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1